### ISSUE TITLE
投稿フォームの追加、リッチテキストエディターを使用

### ISSUE THREAD

**Issue by vigier0709** [vigier0709/portfolio#4]

**Comment by S-H-GAMELINKS** [comment]
`Basecamp`が開発している[`Trix`](https://github.com/basecamp/trix)を使用するか、[wysiwyg-rails](https://github.com/froala/wysiwyg-rails)を使用することで実装したいと思います

**Comment by S-H-GAMELINKS** [comment]
なお、`Trix`で画像のアップロードを行う場合は以下を参照して実装します

ref: [File attachment in toolbar #229](https://github.com/basecamp/trix/issues/229)

**Comment by S-H-GAMELINKS** [comment]
146247531132aa9f3229d5e6178281adb3f58541

ecf71546558d1a3109d310a8ef1a974d82d9dbc6

**Comment by S-H-GAMELINKS** [comment]
#25 で画像の投稿機能は実装できます
