### ISSUE TITLE
会員機能(Deviseを使用し、ログイン/ログアウト機能を実装。退会機能に関しては見送り)

### ISSUE THREAD

**Issue by vigier0709** [vigier0709/portfolio#9]

**Comment by S-H-GAMELINKS** [comment]
[devise](https://github.com/plataformatec/devise)を使用して会員機能を実装します

`Gemfile`に`gem 'devise'`を追加し、`bundle install`を実行

```ruby:Gemfile
gem 'devise'
```

その後、以下のコマンドを実行する

```shell
rails g devise:install
rails g devise:views
rails g devise user
```

最後に、`config/initializers/devise.rb`に以下のコードを追加

```ruby:config/initializers/devise.rb
 config.scoped_views = true
```

後は、`app/views/users`ディレクトリ以下のログイン画面をカスタマイズする
